# Site settings
title: Fabíola Nogueira - Professional Makeup Artist
email: gnfabiola@gmail.com
phone: (45) 9985-6510
description: > # this means to ignore newlines until "baseurl:"
  Fabíola Nogueira - Professional Makeup Artist Makeup, Makeup, Hair, Photos, Weddings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fabiolanogueira.com" # the base hostname & protocol for your site
fullurl: "http://www.fabiolanogueira.com/"
facebook_username: FabiolaNogueiraMakeUpStudio
author: Fabíola Nogueira

# Build settings
markdown: kramdown
exclude: [README.md, README-DEV.md, Gemfile, Gemfile.lock, Rakefile]

#APIs
simple_form_key: 7c0199bc3fccf0f945164a6d49651934

# Blog
permalink: /blog/:year/:month/:day/:title.html
paginate: 1
paginate_path: "/blog/page/:num/"
excerpt_separator: "<!-- more -->"
